[versions]
agp = "8.7.2"
kotlin = "2.0.21"
kotlinCompatibility = "1.5.14"

[libraries]


[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
